"""add relationship

Revision ID: 26b33a2875e1
Revises: 6df8a64e635b
Create Date: 2023-07-06 15:52:15.472958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b33a2875e1'
down_revision = '6df8a64e635b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'board_image', 'board', ['board_id'], ['private_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_image', type_='foreignkey')
    # ### end Alembic commands ###
