"""add relationship of board with rentalbusinessuser

Revision ID: c1fec3f6996d
Revises: 26b33a2875e1
Create Date: 2023-07-06 15:58:47.163254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fec3f6996d'
down_revision = '26b33a2875e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'board', 'rental_business_user', ['rental_business_user_id'], ['private_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    # ### end Alembic commands ###
