"""info_images

Revision ID: ddaf7113ef13
Revises: 4dae63071066
Create Date: 2023-04-02 18:47:26.796251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaf7113ef13'
down_revision = '4dae63071066'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_business_user_info_image',
    sa.Column('private_id', sa.Integer(), nullable=False),
    sa.Column('rental_business_user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('private_id'),
    sa.UniqueConstraint('rental_business_user_id')
    )
    op.create_index(op.f('ix_rental_business_user_info_image_private_id'), 'rental_business_user_info_image', ['private_id'], unique=False)
    op.create_table('rental_business_user_info_image_main',
    sa.Column('private_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('rental_business_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('private_id'),
    sa.UniqueConstraint('image_id'),
    sa.UniqueConstraint('rental_business_user_id')
    )
    op.create_index(op.f('ix_rental_business_user_info_image_main_private_id'), 'rental_business_user_info_image_main', ['private_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_business_user_info_image_main_private_id'), table_name='rental_business_user_info_image_main')
    op.drop_table('rental_business_user_info_image_main')
    op.drop_index(op.f('ix_rental_business_user_info_image_private_id'), table_name='rental_business_user_info_image')
    op.drop_table('rental_business_user_info_image')
    # ### end Alembic commands ###
